### Visualización de Resultados

```{r}
readRenviron("/home/vikto/work/bioinf/sopg/SOPG-Obesidad/report/.Renviron")

library(dplyr)
library(ggplot2)

PROJECT_DIR <- Sys.getenv("PROJECT_DIR")

map <- read.csv(paste0(PROJECT_DIR, "/results/mapeo_genes.csv"), row.names = 1)

load_de_results <- function(results_path) {

  res <- read.csv(
    paste0(PROJECT_DIR, "/results/deseq2/", results_path, ".csv"),
    row.names = 1
  )

  res_df <- as.data.frame(res) |>
    tibble::rownames_to_column(var = "gene") |>
    dplyr::left_join(
      map |> dplyr::select(ensembl_id_clean, gene_symbol),
      by = c("gene" = "ensembl_id_clean")
    ) |>
    dplyr::mutate(
      label = ifelse(
        is.na(gene_symbol) | gene_symbol == gene,
        gene,
        gene_symbol
      )
    )

  return(res_df)
}
```

```{r}
library(EnhancedVolcano)

res_df <- load_de_results("de_sex_age_condition")

p <- EnhancedVolcano(
  res_df,
  lab = res_df$label,
  x = "log2FoldChange",
  y = "pvalue",
  pCutoff = 0.05,
  FCcutoff = 1,
  title = "DESeq2 Volcano"
)
p

ggsave(
  filename = paste0(PROJECT_DIR, "/results/plots/de_sex_age_condition.png"),
  plot = p,
  width = 8,
  height = 6,
  dpi = 300
)
```

```{r}
library(EnhancedVolcano)

res_df <- load_de_results("de_condition")

p <- EnhancedVolcano(
  res_df,
  lab = res_df$label,
  x = "log2FoldChange",
  y = "pvalue",
  pCutoff = 0.05,
  FCcutoff = 1,
  title = "DESeq2 Volcano"
)
p

ggsave(
  filename = paste0(PROJECT_DIR, "/results/plots/de_condition.png"),
  plot = p,
  width = 8,
  height = 6,
  dpi = 300
)
```

```{r}
library(DESeq2)
library(tibble)
library(dplyr)

res_df <- load_de_results("de_sex_age_condition")
dds <- readRDS(paste0(PROJECT_DIR, "/results/deseq2/de_sex_age_condition.rds"))
coldata <- read.csv(paste0(PROJECT_DIR, "/data/design_metadata_corrected.csv"), row.names=1)

# Factores
coldata$condition <- factor(
  coldata$condition,
  levels = c(1, 2),
  labels = c("control", "obese")
)

coldata$sex <- factor(
  coldata$sex,
  levels = c(1, 2),
  labels = c("male", "female")
)

# Numérica (explícito, por higiene)
coldata$age <- as.numeric(coldata$age)

res_sex <- results(dds, name = "sex_female_vs_male") |>
  as.data.frame() |>
  rownames_to_column("gene") |>
  select(gene, log2FC_sex = log2FoldChange)

res_age <- results(dds, name = "age") |>
  as.data.frame() |>
  rownames_to_column("gene") |>
  select(gene, log2FC_age = log2FoldChange)

res_condition <- results(dds, name = "condition_obese_vs_control") |>
  as.data.frame() |>
  rownames_to_column("gene") |>
  select(gene,
         log2FC_condition = log2FoldChange,
         padj)

res_df <- res_condition |>
  left_join(res_sex, by = "gene") |>
  left_join(res_age, by = "gene")

res_df <- res_df |> left_join(map, by = c("gene" = "ensembl_id_clean"))
res_df$label <- ifelse(is.na(res_df$gene_symbol), res_df$gene, res_df$gene_symbol)

res_plot <- res_df |>
  filter(!is.na(padj)) |>
  arrange(padj) |>
  slice_head(n = 42)
```


```{r}
library(circlize)

genes <- res_plot$gene

fc_col <- colorRamp2(
  c(-2, 0, 2),
  c("#2166ac", "white", "#b2182b")
)

circos.clear()
circos.par(
  start.degree = 90,
  gap.degree = 3,
  cell.padding = c(0, 0, 0, 0),
  track.margin = c(0.005, 0.005)
)

# Anillo 1 — condition
circos.heatmap(
  matrix(res_plot$log2FC_condition, ncol = 1),
  split = res_plot$gene,
  col = fc_col,
  cluster = FALSE,
  track.height = 0.09,
  bg.border = NA
)

# Anillo 2 — sex
circos.heatmap(
  matrix(res_plot$log2FC_sex, ncol = 1),
  split = res_plot$gene,
  col = fc_col,
  cluster = FALSE,
  track.height = 0.09,
  bg.border = NA
)

# Anillo 3 — age
circos.heatmap(
  matrix(res_plot$log2FC_age, ncol = 1),
  split = res_plot$gene,
  col = fc_col,
  cluster = FALSE,
  track.height = 0.09,
  bg.border = NA
)

# Gene lables
res_plot$label <- ifelse(
  is.na(res_plot$gene_symbol) | res_plot$gene_symbol == "",
  res_plot$gene,
  res_plot$gene_symbol
)
circos.track(
  ylim = c(0, 1),
  track.height = 0.38,
  bg.border = NA,
  panel.fun = function(x, y) {

    i <- CELL_META$sector.numeric.index

    theta <- as.numeric(CELL_META$theta)[1]
    rot   <- if (theta < -90 || theta > 90) theta + 180 else theta

    circos.segments(
      x0 = CELL_META$xcenter, y0 = 0.92,
      x1 = CELL_META$xcenter, y1 = 1.05,
      col = "grey50",
      lwd = 0.8
    )

    circos.text(
      x = CELL_META$xcenter,
      y = 1.12,
      labels = res_plot$label[i],
      srt = rot,
      facing = "inside",
      niceFacing = FALSE,
      adj = c(0.5, 0),
      cex = 0.6,
      gp = grid::gpar(fontface = "italic")
    )
  }
)

# Anadir nombres a los anillos
ring_names <- c(
  "Condition\n(obese vs control)",
  "Sex\n(female vs male)",
  "Age"
)

ring_y <- c(0.62, 0.54, 0.46)

for (i in seq_along(ring_names)) {
  grid::grid.text(
    ring_names[i],
    x = 0.5,
    y = ring_y[i],
    gp = grid::gpar(fontsize = 9, fontface = "bold")
  )
}

# Generar legenda
library(circlize)
library(grid)

fc_legend <- Legend(
  title = "log2 fold change",
  col_fun = fc_col,
  at = c(-2, -1, 0, 1, 2),
  labels = c("-2", "-1", "0", "1", "2")
)

sig_legend <- Legend(
  title = "Significance",
  labels = c("FDR < 0.01", "FDR < 0.05"),
  legend_gp = grid::gpar(col = c("darkgreen", "darkorange")),
  type = "points",
  pch = c(16, 16)
)

draw(
  packLegend(fc_legend, sig_legend),
  x = unit(0.85, "npc"),
  y = unit(0.5, "npc"),
  just = c("left", "center")
)
```